# Create a new environment using:
# conda env create -f environment.yml

name: kopia-mon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - jinja2>=3.1.2
  - pyyaml>=6.0.1
  - python-dateutil
  - pip
  - pip:
    - dataclasses-json>=0.5.7

